# Generated by Django 5.1.15 on 2026-09-25 13:53

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=api.models.generate_notif_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('offer', 'Offer'), ('reward', 'Reward'), ('order', 'Order'), ('update', 'Update')], default='update', max_length=32)),
                ('read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=api.models.generate_order_id, max_length=64, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_email', models.CharField(blank=True, default='', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loyalty_points_used', models.IntegerField(default=0)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('collected', 'Collected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='paid', max_length=32)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI Payment'), ('card', 'Debit / Credit Card'), ('counter_cash', 'Counter Cash')], default='upi', max_length=32)),
                ('payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('exit_pass_qr', models.TextField(blank=True, default='')),
                ('exit_pass_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(default=api.models.generate_shop_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, default='', max_length=1024)),
                ('cover_url', models.URLField(blank=True, default='', max_length=1024)),
                ('lat', models.FloatField(default=12.9248)),
                ('lng', models.FloatField(default=77.5218)),
                ('distance_m', models.IntegerField(default=300)),
                ('rating', models.FloatField(default=4.5)),
                ('review_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('product_count', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('hours', models.CharField(default='8:00 AM - 10:00 PM', max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('area', models.CharField(default='Rajarajeshwari Nagar', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('supports_self_checkout', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=True)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=api.models.generate_prod_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_pct', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=10)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.shop')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.shop'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.CharField(default=api.models.generate_offer_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount'), ('bogo', 'Buy 1 Get 1')], default='percentage', max_length=32)),
                ('value', models.IntegerField(default=10)),
                ('code', models.CharField(max_length=64)),
                ('valid_from', models.CharField(default='', max_length=64)),
                ('valid_to', models.CharField(default='', max_length=64)),
                ('banner_gradient', models.CharField(default='from-amber-500 to-orange-600', max_length=255)),
                ('applicable_categories', models.JSONField(blank=True, default=list)),
                ('min_order_value', models.IntegerField(default=0)),
                ('is_ending_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.shop')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.CharField(default=api.models.generate_loyalty_id, max_length=64, primary_key=True, serialize=False)),
                ('user_phone', models.CharField(blank=True, default='', max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('next_reward_at', models.IntegerField(default=200)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Silver', max_length=32)),
                ('barcode', models.CharField(default='', max_length=64)),
                ('available_rewards', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='api.shop')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.CharField(default=api.models.generate_post_id, max_length=64, primary_key=True, serialize=False)),
                ('area', models.CharField(default='', max_length=200)),
                ('time_ago', models.CharField(default='Just now', max_length=100)),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('offer_tag', models.CharField(blank=True, default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='api.shop')),
            ],
        ),
    ]
